import { z } from "zod";

// ---------------------------------------------------------------------------
// Data contract (version 1, additive). Everything here is computed by the
// customer's own evaluator; the workspace never runs inference.
//
//  - baseline_error / candidate_error: per-case mean endpoint error (px).
//  - baseline_frames / candidate_frames: optional paired per-frame EPE series.
//  - baseline_trajectory / candidate_trajectory: optional, label-free.
//    One number per refinement iteration of the model: the mean magnitude of
//    that iteration's update (px). For RAFT-style models this is
//    `abs(delta_flow).mean()` inside the update loop. No ground truth needed.
// ---------------------------------------------------------------------------

const score = z.number().finite().min(0).max(1000000);
const series = z.array(score).min(2).max(512);
const trajectory = z.array(score).min(2).max(64);

const caseSchema = z.object({
  id: z.string().regex(/^[a-zA-Z0-9_.-]{1,80}$/),
  name: z.string().trim().min(1).max(120),
  tags: z.array(z.string().max(40)).max(8).default([]),
  baseline_error: score,
  candidate_error: score,
  baseline_frames: series.optional(),
  candidate_frames: series.optional(),
  baseline_trajectory: trajectory.optional(),
  candidate_trajectory: trajectory.optional(),
  notes: z.string().max(1000).optional(),
}).superRefine((v, ctx) => {
  if (Boolean(v.baseline_frames) !== Boolean(v.candidate_frames) || (v.baseline_frames && v.baseline_frames.length !== v.candidate_frames?.length)) ctx.addIssue({ code: z.ZodIssueCode.custom, message: "Frame series must be paired and have equal lengths." });
});

// `metric` names any lower-is-better error metric; `unit` is its unit as shown in labels
// (px for optical flow, cm or m for depth, ...). Legacy files that used the literal
// metric "mean_endpoint_error_px" still import; their unit is px.
export const comparisonSchema = z.object({
  version: z.literal(1),
  project: z.string().trim().min(1).max(100),
  baseline: z.string().trim().min(1).max(100),
  candidate: z.string().trim().min(1).max(100),
  dataset: z.string().trim().min(1).max(120),
  metric: z.string().trim().min(1).max(60),
  unit: z.string().trim().min(1).max(16).optional(),
  source: z.enum(["example", "imported"]).optional(),
  cases: z.array(caseSchema).min(1).max(500),
}).superRefine((v, ctx) => {
  if (new Set(v.cases.map(c => c.id)).size !== v.cases.length) ctx.addIssue({ code: z.ZodIssueCode.custom, message: "Case IDs must be unique." });
});
export function metricLabel(run: { metric: string; unit?: string }) {
  const name = run.metric.replace(/_px$/, "").replace(/_/g, " ");
  return name === "mean endpoint error" ? "mean endpoint error" : name;
}
export function unitOf(run: { metric: string; unit?: string }) { return run.unit ?? (run.metric.endsWith("_px") ? "px" : "units"); }
export type Comparison = z.infer<typeof comparisonSchema>;
export type ComparisonCase = Comparison["cases"][number];

// A saved check is an absolute limit for a stable case ID in a named project.
// max_error: candidate EPE must stay at or below it.
// max_late_share (optional): the candidate's trajectory must also be settled:
// at most this share of its refinement may happen in the last third of its iterations.
// max_reversals (optional): and its update may grow again at most this many times.
export const checkSchema = z.object({
  id: z.string().regex(/^[a-zA-Z0-9_.-]{1,80}$/),
  name: z.string().max(120),
  project: z.string().max(100),
  max_error: score,
  max_late_share: z.number().finite().min(0).max(1).optional(),
  max_reversals: z.number().int().min(0).max(64).optional(),
});
export type SavedCheck = z.infer<typeof checkSchema>;

// Limits the reviewer chooses. `threshold` flags error increases; the rest decide
// when a trajectory counts as unstable. The names differ from the CLI's; they are
// the same limits and are checked against each other by the conformance test:
//
//   threshold            max_regression
//   lateShare            max_late_share
//   reversals            max_reversals
//   lastUpdate           max_last_update              (off when absent)
//   trajectoryRegression max_trajectory_regression    (off when absent)
//
// The last two are off by default here and in the CLI, but `rb init` turns
// trajectoryRegression on for every new project, so a report generated by the CLI
// usually arrives with it set. A viewer that ignored it would call cases settled
// that rb calls unstable.
export const limitsSchema = z.object({
  threshold: score,
  lateShare: z.number().finite().min(0).max(1),
  reversals: z.number().int().min(0).max(64),
  lastUpdate: score.nullish(),
  trajectoryRegression: score.nullish(),
});
export type Limits = z.infer<typeof limitsSchema>;
export const DEFAULT_LIMITS: Limits = { threshold: 0.3, lateShare: 0.25, reversals: 2 };

// ---------------------------------------------------------------------------
// Trajectory stability. Deliberately simple and explainable; check.py in the
// integration kit implements exactly the same arithmetic.
//
//  lateShare  = sum(updates in the last third of iterations) / sum(all updates)
//  reversals  = iterations where the update grew by more than 5% over the previous one
//  settled    = lateShare <= limits.lateShare && reversals <= limits.reversals
//
// A model that has converged keeps shrinking its updates; one that keeps
// revising its answer late, or re-opens it, is unstable on that case even when
// the final error happens to land close to the current model.
// ---------------------------------------------------------------------------

export type TrajectoryStats = { iterations: number; lateShare: number; reversals: number; peakIteration: number; total: number; lastUpdate: number; lateUpdate: number };
export function trajectoryStats(t: number[]): TrajectoryStats {
  const total = t.reduce((a, b) => a + b, 0);
  const start = Math.floor(t.length * 2 / 3);
  const late = t.slice(start).reduce((a, b) => a + b, 0);
  let reversals = 0;
  for (let i = 1; i < t.length; i++) if (t[i] > t[i - 1] * 1.05 + 1e-9) reversals++;
  let peakIteration = 0;
  for (let i = 1; i < t.length; i++) if (t[i] > t[peakIteration]) peakIteration = i;
  // The last quarter, the window the convergence limits are measured over. Both are absolute
  // magnitudes in the metric's unit, unlike lateShare which is a fraction of the whole.
  const quarter = Math.max(1, Math.floor(t.length / 4));
  const lateUpdate = t.slice(-quarter).reduce((a, b) => a + b, 0) / quarter;
  return { iterations: t.length, lateShare: total > 0 ? late / total : 0, reversals, peakIteration, total, lastUpdate: t[t.length - 1], lateUpdate };
}
export function isSettled(stats: TrajectoryStats, limits: Limits) {
  if (stats.lateShare > limits.lateShare + 1e-9 || stats.reversals > limits.reversals) return false;
  if (limits.lastUpdate != null && stats.lastUpdate > limits.lastUpdate + 1e-9) return false;
  return true;
}
export function lateStart(length: number) { return Math.floor(length * 2 / 3); }

// Candidate late movement minus the current model's on the same case. Paired and label-free, so it
// applies to cases without ground truth exactly as the error limit applies to cases with it.
export function trajectoryChange(c: ComparisonCase): number | null {
  if (!c.baseline_trajectory || !c.candidate_trajectory) return null;
  return trajectoryStats(c.candidate_trajectory).lateUpdate - trajectoryStats(c.baseline_trajectory).lateUpdate;
}
export function trajectoryRegressed(c: ComparisonCase, limits: Limits) {
  if (limits.trajectoryRegression == null) return false;
  const d = trajectoryChange(c);
  return d !== null && d > limits.trajectoryRegression + 1e-9;
}

export type ErrorOutcome = "regression" | "improved" | "stable";
export type StabilityOutcome = "unstable" | "settled" | "unknown";

export function delta(c: ComparisonCase) { return c.candidate_error - c.baseline_error; }
export function outcome(c: ComparisonCase, threshold: number): ErrorOutcome { return delta(c) > threshold + 1e-9 ? "regression" : delta(c) < -threshold - 1e-9 ? "improved" : "stable"; }
export function stabilityOutcome(c: ComparisonCase, limits: Limits): StabilityOutcome {
  if (!c.candidate_trajectory) return "unknown";
  if (!isSettled(trajectoryStats(c.candidate_trajectory), limits) || trajectoryRegressed(c, limits)) return "unstable";
  return "settled";
}
export function isFlagged(c: ComparisonCase, limits: Limits) { return outcome(c, limits.threshold) === "regression" || stabilityOutcome(c, limits) === "unstable"; }
// Ordering for the case list: cases that need a decision first, largest error increase within each group.
export function priority(c: ComparisonCase, limits: Limits) {
  const regression = outcome(c, limits.threshold) === "regression", unstable = stabilityOutcome(c, limits) === "unstable";
  return regression && unstable ? 3 : regression ? 2 : unstable ? 1 : 0;
}
export function rank(cases: ComparisonCase[], limits: Limits) {
  return [...cases].sort((a, b) => priority(b, limits) - priority(a, limits) || delta(b) - delta(a));
}

export function summary(run: Comparison, limits: Limits) {
  const baseline = run.cases.reduce((n, c) => n + c.baseline_error, 0) / run.cases.length;
  const candidate = run.cases.reduce((n, c) => n + c.candidate_error, 0) / run.cases.length;
  const unstableCases = run.cases.filter(c => stabilityOutcome(c, limits) === "unstable");
  return {
    baseline, candidate, change: baseline ? (candidate - baseline) / baseline * 100 : null,
    regressions: run.cases.filter(c => outcome(c, limits.threshold) === "regression").length,
    improved: run.cases.filter(c => outcome(c, limits.threshold) === "improved").length,
    unstable: unstableCases.length,
    unstablePassing: unstableCases.filter(c => outcome(c, limits.threshold) !== "regression").length,
    withTrajectories: run.cases.filter(c => c.candidate_trajectory).length,
    flagged: run.cases.filter(c => isFlagged(c, limits)).length,
  };
}
// One line an engineer can act on, above the list. `ready` reads the cases alone; a saved check that
// fails or has lost its case is reported in the same line but does not change it, which is how rb
// records the two facts separately.
export type VerdictStatus = "clear" | "investigate" | "checks_failing";
export function verdict(run: Comparison, limits: Limits, checks: SavedCheck[] = []) {
  const s = summary(run, limits);
  const first = rank(run.cases, limits)[0];
  const ready = s.flagged === 0;
  let text: string;
  if (ready) text = s.withTrajectories > 0 ? `Nothing flagged: no error regressions, every candidate trajectory settled.` : `Nothing flagged: no error regressions. Export trajectories to assess stability too.`;
  else {
    const parts: string[] = [];
    if (s.regressions) parts.push(`${s.regressions} error regression${s.regressions === 1 ? "" : "s"}`);
    if (s.unstablePassing) parts.push(`${s.unstablePassing} unstable ${s.unstablePassing === 1 ? "case that passes" : "cases that pass"} on error`);
    else if (s.unstable) parts.push(`${s.unstable} unstable case${s.unstable === 1 ? "" : "s"}`);
    text = `Not ready: ${parts.join(", ")}.`;
  }
  // A missing case counts with the failures: a check whose case left the run is not a check that passed.
  const n = checks.filter(c => c.project === run.project)
    .filter(c => { const st = checkStatus(c, run); return st === "failing" || st === "missing"; }).length;
  if (n) text = ready ? `${n} saved check${n === 1 ? "" : "s"} failing. ${text}` : text.replace(/\.$/, "") + `; ${n} saved check${n === 1 ? "" : "s"} failing.`;
  const status: VerdictStatus = n ? "checks_failing" : ready ? "clear" : "investigate";
  return { ready, status, text, start: ready ? null : (first.id as string | null), startName: ready ? "" : first.name };
}

export type CheckStatus = "other-project" | "missing" | "failing" | "passing";
export function checkResult(check: SavedCheck, run: Comparison): { status: CheckStatus; reason: string } {
  if (check.project !== run.project) return { status: "other-project", reason: "Saved for another project." };
  const found = run.cases.find(c => c.id === check.id);
  if (!found) return { status: "missing", reason: "Case not present in this comparison." };
  if (found.candidate_error > check.max_error + 1e-9) return { status: "failing", reason: `Candidate error ${found.candidate_error.toFixed(2)} ${unitOf(run)} exceeds the ${check.max_error.toFixed(2)} ${unitOf(run)} limit.` };
  if (check.max_late_share !== undefined || check.max_reversals !== undefined) {
    if (!found.candidate_trajectory) return { status: "failing", reason: "This check requires a settled trajectory, but none was exported for the candidate." };
    const stats = trajectoryStats(found.candidate_trajectory);
    if (check.max_late_share !== undefined && stats.lateShare > check.max_late_share + 1e-9) return { status: "failing", reason: `Late revision ${Math.round(stats.lateShare * 100)}% exceeds the ${Math.round(check.max_late_share * 100)}% limit.` };
    if (check.max_reversals !== undefined && stats.reversals > check.max_reversals) return { status: "failing", reason: `Reversals ${stats.reversals} exceed the ${check.max_reversals} limit.` };
  }
  return { status: "passing", reason: "Within limits." };
}
export function checkStatus(check: SavedCheck, run: Comparison): CheckStatus { return checkResult(check, run).status; }

export class ImportError extends Error {
  problems: string[];
  constructor(problems: string[]) { super(problems.join("\n")); this.problems = problems; }
}
const REQUIREMENT: Record<string, string> = {
  version: "the number 1", project: "a short project name", baseline: "the current model's name", candidate: "the candidate model's name",
  dataset: "the evaluation set's name", metric: "an error metric name such as mean_endpoint_error", unit: "a short unit such as px or cm",
  baseline_error: "a nonnegative number", candidate_error: "a nonnegative number", id: "1–80 characters of letters, digits, _ . or -", name: "a short name",
  baseline_frames: "2–512 nonnegative numbers", candidate_frames: "2–512 nonnegative numbers",
  baseline_trajectory: "2–64 nonnegative numbers, one per refinement iteration", candidate_trajectory: "2–64 nonnegative numbers, one per refinement iteration",
  cases: "a list of 1–500 cases",
};
function describe(issue: z.ZodIssue, value: unknown): string {
  const path = issue.path;
  let label = "";
  if (path[0] === "cases" && typeof path[1] === "number") {
    const cases = (value as { cases?: unknown[] })?.cases;
    const item = Array.isArray(cases) ? cases[path[1]] as { id?: unknown } : undefined;
    label = item && typeof item.id === "string" ? `Case ${path[1] + 1} (${item.id}): ` : `Case ${path[1] + 1}: `;
    if (path.length === 2 && issue.code !== "custom") return `${label}must be an object with id, name, baseline_error and candidate_error.`;
  }
  if (issue.code === "custom") return `${label}${issue.message}`;
  const field = String(path[path.length - 1] ?? "");
  const key = typeof path[path.length - 1] === "number" ? String(path[path.length - 2] ?? "") : field;
  if (!key) return "The file must be a JSON object.";
  const requirement = REQUIREMENT[key] ?? issue.message.toLowerCase();
  const missing = issue.code === "invalid_type" && (issue as { received?: string }).received === "undefined";
  return missing ? `${label}${key} is missing: add ${requirement}.` : `${label}${key} must be ${requirement}.`;
}
export function parseComparison(raw: string): Comparison {
  if (new TextEncoder().encode(raw).length > 2_000_000) throw new ImportError(["Use a results file under 2 MB (up to 500 cases)."]);
  let value: unknown;
  try { value = JSON.parse(raw); } catch { throw new ImportError(["This is not valid JSON. Check for a missing comma or bracket, or start from the minimal example below."]); }
  const parsed = comparisonSchema.safeParse(value);
  if (!parsed.success) {
    const seen = new Set<string>(); const problems: string[] = [];
    for (const issue of parsed.error.issues) { const text = describe(issue, value); if (!seen.has(text)) { seen.add(text); problems.push(text); } }
    const shown = problems.slice(0, 10); if (problems.length > 10) shown.push(`…and ${problems.length - 10} more.`);
    throw new ImportError(shown);
  }
  return { ...parsed.data, source: parsed.data.source === "example" ? "example" : "imported" };
}
export const MINIMAL_EXAMPLE = `{
  "version": 1,
  "project": "My perception project",
  "baseline": "model-v1", "candidate": "model-v2",
  "dataset": "Regression set", "metric": "mean_endpoint_error", "unit": "px",
  "cases": [
    { "id": "seq-001", "name": "First sequence", "baseline_error": 2.1, "candidate_error": 2.4,
      "candidate_trajectory": [2.3, 1.4, 0.9, 0.6, 0.4, 0.3, 0.2, 0.15, 0.1, 0.08, 0.06, 0.05] }
  ]
}`;

const fmt = (v: number) => v.toFixed(2);
const pct = (v: number) => `${Math.round(v * 100)}%`;
export function reportMarkdown(run: Comparison, limits: Limits, checks: SavedCheck[]) {
  const s = summary(run, limits);
  const withTrajectories = s.withTrajectories > 0;
  const row = (c: ComparisonCase) => {
    const stab = c.candidate_trajectory ? trajectoryStats(c.candidate_trajectory) : null;
    const base = `| ${c.id} | ${fmt(c.baseline_error)} | ${fmt(c.candidate_error)} | ${fmt(delta(c))} | ${outcome(c, limits.threshold)} |`;
    return withTrajectories ? `${base} ${stab ? `${pct(stab.lateShare)} · ${stab.reversals} rev.` : "n/a"} | ${stabilityOutcome(c, limits)} |` : base;
  };
  const unit = unitOf(run);
  return `# ${run.project}: model comparison\n\n${run.source === "example" ? "The worked example, not your own run: real output from a recorded comparison of two public checkpoints.\n\n" : "Imported evaluation results.\n\n"}Current: ${run.baseline}\nCandidate: ${run.candidate}\nDataset: ${run.dataset}\nMetric: ${metricLabel(run)} (${unit}), lower is better.\n\nMean of case errors: ${fmt(s.baseline)} → ${fmt(s.candidate)} ${unit}. Cases are weighted equally; this is not a pooled per-pixel mean.\nRegression threshold: increase greater than ${limits.threshold} ${unit}.\n${s.regressions} of ${run.cases.length} cases regress on error.\n${withTrajectories ? `Stability limits: late revision ≤ ${pct(limits.lateShare)}, reversals ≤ ${limits.reversals}. ${s.unstable} of ${s.withTrajectories} cases with trajectories are unstable; ${s.unstablePassing} of those pass on error.\n` : "No refinement trajectories were exported, so stability was not assessed.\n"}\n| Case | Current (${unit}) | Candidate (${unit}) | Change (${unit}) | Error |${withTrajectories ? " Candidate late revision | Stability |" : ""}\n|---|---:|---:|---:|---|${withTrajectories ? "---|---|" : ""}\n${rank(run.cases, limits).map(row).join("\n")}\n\n## Saved checks\n${checks.filter(c => c.project === run.project).map(c => `- ${c.id}: candidate error ≤ ${fmt(c.max_error)} ${unit}${c.max_late_share !== undefined ? `, late revision ≤ ${pct(c.max_late_share)}` : ""}: ${checkResult(c, run).status}`).join("\n") || "No saved checks for this project."}\n\nThe check runner evaluates these supplied metrics and trajectories against the limits. It does not run inference or certify a model for deployment.\n`;
}

// ---------------------------------------------------------------------------
// Illustrative example: a warehouse robot's optical-flow model, v2.3 → v2.4.
// Synthetic numbers shaped to show the workflow. Not measured results.
// ---------------------------------------------------------------------------

type Shape = "settled" | "late" | "drift";
const specs: [string, string, string[], number, number, Shape, Shape, string?][] = [
  ["aisle-042", "Reflective floor", ["warehouse", "reflection"], 3.4, 5.2, "settled", "late", "The candidate's error rises mid-sequence and its refinement never settles: most of its revisions arrive late. Investigate before release."],
  ["loading-018", "Loading-bay transition", ["low light", "exposure"], 2.6, 4.0, "settled", "settled", "Error regressed, but the candidate converged cleanly. It is confidently worse here: a data or training gap, not instability."],
  ["crossing-007", "Fast crossing motion", ["occlusion", "motion"], 3.8, 4.7, "late", "late", "Both models keep revising this case late. The candidate adds error on top. Consider it a known hard case and keep a check on it."],
  ["aisle-011", "Long aisle", ["warehouse", "texture"], 2.9, 1.9, "settled", "drift", "Error improved, yet the candidate's updates grow again through its final iterations. The better number is not a settled answer."],
  ["turn-026", "Tight corner", ["rotation"], 3.2, 2.1, "settled", "late", "Error improved, but the candidate re-opened its estimate late in the loop. Treat as unreliable until it holds on more sequences."],
  ["pallet-003", "Pallet approach", ["close range"], 4.3, 2.9, "settled", "settled"],
  ["aisle-024", "Open aisle", ["warehouse"], 2.7, 1.7, "settled", "settled"],
  ["loading-021", "Ramp descent", ["slope"], 3.6, 2.3, "settled", "settled"],
  ["static-006", "Stopped at station", ["stationary"], 1.7, 1.1, "settled", "settled"],
  ["turn-012", "Wide turn", ["rotation"], 2.8, 1.9, "settled", "settled"],
  ["crossing-019", "Passing equipment", ["occlusion"], 4.2, 2.9, "settled", "settled"],
  ["aisle-031", "Daylight aisle", ["daylight"], 2.3, 1.6, "settled", "settled"],
];
function frameSeries(mean: number, regression: boolean) {
  const shape = regression
    ? [.58, .63, .67, .70, .82, 1.06, 1.46, 1.75, 1.68, 1.57, 1.32, 1.04, .89, .80, .69, .64]
    : [.86, .90, .95, 1.06, 1.08, .98, 1.14, 1.16, 1.03, .94, 1.06, 1.01, .94, 1.04, .96, .89];
  const scale = mean / (shape.reduce((a, b) => a + b, 0) / shape.length);
  return shape.map(v => Number((v * scale).toFixed(3)));
}
// Update magnitude per refinement iteration (12 iterations). Shapes are scaled by the case's error so numbers vary.
function trajectoryShape(kind: Shape, error: number) {
  const shape = kind === "settled" ? [2.40, 1.52, .96, .63, .42, .29, .21, .15, .11, .08, .06, .05]
    : kind === "late" ? [2.30, 1.42, .90, .60, .43, .36, .31, .55, .84, .92, .78, .66]
    : [2.20, 1.30, .80, .55, .45, .42, .41, .44, .50, .58, .64, .70];
  const scale = 0.55 + error / 6;
  return shape.map(v => Number((v * scale).toFixed(3)));
}
export const EXAMPLE: Comparison = {
  version: 1, project: "Warehouse perception", baseline: "flow-v2.3", candidate: "flow-v2.4",
  dataset: "Warehouse regression set", metric: "mean_endpoint_error", unit: "px", source: "example",
  cases: specs.map(([id, name, tags, b, c, baseShape, candShape, notes], i) => ({
    id, name, tags, baseline_error: b, candidate_error: c,
    baseline_frames: frameSeries(b, false), candidate_frames: frameSeries(c, i < 3),
    baseline_trajectory: trajectoryShape(baseShape, b), candidate_trajectory: trajectoryShape(candShape, c),
    notes,
  })),
};
